version: "3.11"
services:
  db:
    image: postgres:13
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db