"""1

Revision ID: b7077d7f5e0b
Revises: 
Create Date: 2023-11-24 22:18:41.587802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from src.users.models import Role


# revision identifiers, used by Alembic.
revision: str = 'b7077d7f5e0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def create_roles(session: Session) -> None:
    roles = [
        {"name": "GUEST", "description": "A Guest Account", "permissions": None},
        {"name": "USER", "description": "Account owner", "permissions": None},
        {"name": "ADMIN", "description": "Admin of Application Ecosystem", "permissions": None},
        {"name": "SUPER_ADMIN", "description": "Super Administrator of Application Ecosystem", "permissions": None},
    ]

    for role_data in roles:
        role = Role(**role_data)
        session.add(role)

    session.commit()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###

    # Викликаємо функцію create_roles під час підняття міграції
    bind = op.get_bind()
    session = Session(bind=bind)
    create_roles(session)
    session.close()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_table('role')
    # ### end Alembic commands ###
