"""2

Revision ID: d376fd333fd2
Revises: c2ed15a8aa25
Create Date: 2023-11-19 03:05:31.900511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd376fd333fd2'
down_revision: Union[str, None] = 'c2ed15a8aa25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'repost', 'video', ['video_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'repost', 'user', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'repost', 'user', ['to_user'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repost', type_='foreignkey')
    op.drop_constraint(None, 'repost', type_='foreignkey')
    op.drop_constraint(None, 'repost', type_='foreignkey')
    # ### end Alembic commands ###
