"""1

ID ревізії: c199def8c4f9
Переглядає: 
Дата створення: 2023-11-27 01:42:54.426970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c199def8c4f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'repost', 'user', ['to_user'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'repost', 'video', ['video_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'repost', 'user', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###

    op.execute(
        """
        INSERT INTO role (name, permissions)
        VALUES
            ('GUEST', '["get_reviews", "view_site"]'),
            ('SELLER', '["create_product", "delete_product"]'),
            ('BUYER', '["buy_product", "add_review", "get_reviews"]'),
            ('ADMIN', '["manage_users", "manage_roles", "manage_products"]');
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'repost', type_='foreignkey')
    op.drop_constraint(None, 'repost', type_='foreignkey')
    op.drop_constraint(None, 'repost', type_='foreignkey')
    op.drop_table('role')
    # ### end Alembic commands ###


    op.execute(
        """
        DELETE FROM role
        WHERE name IN ('GUEST', 'SELLER', 'BUYER', 'ADMIN');
        """
    )
